apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-a-binding
  namespace: wcs
subjects:
  - kind: ServiceAccount
    name: service-a-sa
    namespace: wcs
roleRef:
  kind: Role
  name: service-a-role
  apiGroup: rbac.authorization.k8s.io
